### PR TITLE
Ensure multiples schedules of the same job with different chains of dependent jobs are properly processed

### LINKED ISSUE #108: [MaybeBug/MaybeDoc] Unclear expectations about dependent jobs
**Describe the bug**
Running the same job on different schedules, each schedule having different sub dependent jobs doesn't seem to work.

I've tried to expose this through a test that seems to put the "issue/expectation" under the light.

⚠️ I've been fighting a lot with the integration test infrastructure (ChannelWriter , ...). And I often lost. My understanding of it is very light. So that test may be badly written or failing for the wrong reasons.

I've tried to model something that may exist in real life: Regular internal reporting vs longer delayed external reporting.

As a side note, I've haven't been able to model a test simulating a daily vs a monthly execution and would be interested to know more about how to achieve this.

```csharp
[Fact]
public async Task Hrmpf()
{
    string constantly = "* * * * *";
    string monthly = "0 0 1 * *";

    FakeTimer.SetUtcNow(DateTimeOffset.Parse("2024-10-25T16:55Z", CultureInfo.InvariantCulture));

    var storage = new DepStorage();
    ServiceCollection.AddSingleton(storage);
    ServiceCollection.AddNCronJob(n =>
    {
        n.AddJob<AnalysisJob>(b => b.WithCronExpression(constantly))
            .ExecuteWhen(success: s => s.RunJob<ReportToProductOwnerJob>());

        n.AddJob<AnalysisJob>(b => b.WithCronExpression(monthly))
            .ExecuteWhen(success: s => s.RunJob<ReportToStakeholdersJob>());
    });

    var provider = CreateServiceProvider();
    await provider.GetRequiredService<IHostedService>().StartAsync(CancellationToken);

    FakeTimer.Advance(TimeSpan.FromMinutes(2));

    await Task.WhenAll(GetCompletionJobs(2));
    string.Join(' ', storage.InvokedJobs).ShouldNotContain(nameof(ReportToStakeholdersJob));
}

private sealed class DepStorage
{
    public ConcurrentBag<string> InvokedJobs { get; } = [];
}

private sealed class AnalysisJob(ChannelWriter<object> writer, DepStorage storage) : IJob
{
    public async Task RunAsync(IJobExecutionContext context, CancellationToken token)
    {
        storage.InvokedJobs.Add(context.JobType!.Name);
        await writer.WriteAsync(true, token);
    }
}

private sealed class ReportToProductOwnerJob(ChannelWriter<object> writer, DepStorage storage) : IJob
{
    public async Task RunAsync(IJobExecutionContext context, CancellationToken token)
    {
        storage.InvokedJobs.Add(context.JobType!.Name);
        await writer.WriteAsync(true, token);
    }
}

private sealed class ReportToStakeholdersJob(ChannelWriter<object> writer, DepStorage storage) : IJob
{
    public async Task RunAsync(IJobExecutionContext context, CancellationToken token)
    {
        storage.InvokedJobs.Add(context.JobType!.Name);
        await writer.WriteAsync(true, token);
    }
}
``` 

**Current behavior**
`ReportToProductOwnerJob` is invoked every minute.
`ReportToStakeholdersJob` is invoked every minute.

**Expected behavior**
I can think of 3 options (from "best" to "worse" from the user standpoint):

1. Make it work
   - `ReportToProductOwnerJob` is invoked every minute.
   - `ReportToStakeholdersJob` is invoked every month.

2. Prevent it from happening
   - Make AddNCronJob() throw a NotSupportedException bearing an explicit message when this kind of usage is detected

3. Document that it's not currently supported
   - Add a "Known gotchas" section in the documentation
   - Propose an alternative design that would allow this kind of use case

Although "Make it work" would obviously be the preferred option, my current endeavor in #106 leads me to think that this might not be a one-liner fix.

**Version information**
 - NCronJobVersion: 3.3.2
 - .NET runtime version: irrelevant

### PR DESCRIPTION
**Pull request by nulltoken**
## Pull request description
This partly fixes #108 with regards to not properly honoring different dependent schedules.

However, this doesn't deal with the other broader concerns (for instance, how to selectively run an instant job targeting a specified configured schedule among other ones).

### PR meta checklist
- [x] Pull request is targeted at `main` branch for code   
- [x] Pull request is linked to all related issues, if any.

### Code PR specific checklist
- [ ] My code follows the code style of this project and AspNetCore coding guidelines.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [x] I have updated the appropriate sub section in the _CHANGELOG.md_.
- [x] I have added, updated or removed tests to according to my changes.
  - [x] All tests passed.

### CODE REVIEW

File: src/NCronJob/Registry/JobDefinitionEqualityComparer.cs [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+internal sealed class JobDefinitionEqualityComparer : IEqualityComparer<JobDefinition>
+{
+    public static readonly JobDefinitionEqualityComparer Instance = new();
+
+    public bool Equals(JobDefinition? x, JobDefinition? y) =>
+        x is null && y is null || x is not null && y is not null
+                                     && x.Type == y.Type && x.Type != typeof(DynamicJobFactory)
+                                     && x.Parameter == y.Parameter
+                                     && x.CronExpression == y.CronExpression
+                                     //&& x.TimeZone == y.TimeZone
```
Comment (nulltoken) [inline src/NCronJob/Registry/JobDefinitionEqualityComparer.cs:14]: @linkdotnet That removal partly played some role into being able to identify the jobDefinition in the HashSet. But I feel there are a lot of corner cases where this could blow back.

Thoughts?

wthgcgFiaoLsHkCxVn5oS8

File: src/NCronJob/Registry/JobDefinitionEqualityComparer.cs [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+                                     && x.CustomName == y.CustomName
+                                     && x.IsStartupJob == y.IsStartupJob;
+
+    public int GetHashCode(JobDefinition obj) => HashCode.Combine(
+        obj.Type,
+        obj.Parameter,
+        obj.CronExpression,
+        //obj.TimeZone,
```
Comment (nulltoken) [inline src/NCronJob/Registry/JobDefinitionEqualityComparer.cs:22]: Here as well

File: src/NCronJob/Registry/JobRegistry.cs [hunk 3]
```diff
@@ -19,7 +20,7 @@ internal sealed class JobRegistry
     public JobDefinition GetJobDefinition<T>() => allJobs.First(j => j.Type == typeof(T));
 
     public JobDefinition? FindJobDefinition(Type type)
-        => allJobs.FirstOrDefault(j => j.Type == type);
+        => allJobs.FirstOrDefault(j => j.Type == type); // TODO: We may have more than one job definition per type
```
Comment (nulltoken) [inline src/NCronJob/Registry/JobRegistry.cs:23]: Dragons, dragons, dragons...

File: src/NCronJob/Registry/JobDefinitionEqualityComparer.cs (hunk 1 above)
Comment (nulltoken) [reply src/NCronJob/Registry/JobDefinitionEqualityComparer.cs:12]: Scratch that. I went a different way and maybe understood one of the underlying problem I was facing here.

File: src/NCronJob/Registry/JobRegistry.cs [hunk 4]
```diff
@@ -168,4 +172,37 @@ public int GetHashCode(JobDefinition obj) => HashCode.Combine(
             obj.CustomName,
             obj.IsStartupJob);
     }
+
+    private sealed class DependentJobDefinitionEqualityComparer : IEqualityComparer<JobDefinition>
+    {
+        // TODO: Maybe is the code conflating two different concepts.
```
Comment (nulltoken) [inline src/NCronJob/Registry/JobRegistry.cs:178]: @linkdotnet Thoughts?

File: src/NCronJob/Registry/JobDefinitionEqualityComparer.cs (hunk 2 above)
Comment (nulltoken) [reply src/NCronJob/Registry/JobDefinitionEqualityComparer.cs:20]: This change has been moved back to JobRegistry

File: src/NCronJob/Registry/JobRegistry.cs (hunk 4 above)
Comment (linkdotnet) [reply src/NCronJob/Registry/JobRegistry.cs:178]: DependentJobDefinition - that is a good question. And I can't answer the question until now.

We need a definition of a dependent job and when it gets triggered. 
Will have a look in more depth later today

File: src/NCronJob/Configuration/Builder/DependentJobRegistryEntry.cs [hunk 5]
```diff
@@ -2,7 +2,6 @@ namespace NCronJob;
 
 internal sealed class DependentJobRegistryEntry
 {
-    public required Type PrincipalType { get; init; }
     public List<JobDefinition> RunWhenSuccess { get; init; } = [];
```
Comment (linkdotnet) [inline src/NCronJob/Configuration/Builder/DependentJobRegistryEntry.cs:5]: Could this life directly on the parent JobDefinition?

I don't see much of a need for `DepdentJobRegistryEntry` (and friends) anymore.

The question is how we can model something like:
```csharp
AddNcronJob(s => {
  s.AddJob<PrincipalJob>(...).ExecuteWhen(r => r.RunJob<DependentJob>());
  s.AddJob<DependentJob>(r => r.WithCronExpression(...)).ExecutenWhen(r => r.RunJob<DepDepJob>());
```

So if `PrincipalJob` runs, `DependentJob` should run afterward and `DepDepJob` after that.

**Comment by linkdotnet** [comment]
One test seems to be stuck:
image

**Comment by linkdotnet** [comment]
Locally I can't reproduce the hanging test, but when running via Github Codespace, it also sometimes hangs. Just doesn't show the current executed test.

**Comment by nulltoken** [comment]
> Locally I can't reproduce the hanging test, but when running via Github Codespace, it also sometimes hangs. Just doesn't show the current executed test.

On it.

**Comment by nulltoken** [comment]
> > Locally I can't reproduce the hanging test, but when running via Github Codespace, it also sometimes hangs. Just doesn't show the current executed test.
> 
> On it.

Can't repro either.
Rebased and added some xunit configuration to list hanging tests in the future.

**Comment by linkdotnet** [comment]
I'll try to reproduce via the Codespace. Just FYI: You can also use codespaces with 120 CPU hours for free.

File: src/NCronJob/Configuration/Builder/DependentJobRegistryEntry.cs (hunk 5 above)
Comment (nulltoken) [reply src/NCronJob/Configuration/Builder/DependentJobRegistryEntry.cs:5]: > Could this life directly on the parent JobDefinition?
> 
> I don't see much of a need for `DepdentJobRegistryEntry` (and friends) anymore.

If that's ok with you, I'd rather work on this in a follow up PR as an internal refactoring.

This one is already a bit "stuffy".

**Comment by linkdotnet** [comment]
It happes on the Codespace **only** on `net9.0`:
image

**CanBuildAChainOfDependentJobsThatRunAfterOneJob**

**Comment by nulltoken** [comment]
> It happes on the Codespace **only** on `net9.0`: image
> **CanBuildAChainOfDependentJobsThatRunAfterOneJob**

Thanks for the identification. I'll take a look at it tomorrow.

**Comment by nulltoken** [comment]
> > It happes on the Codespace **only** on `net9.0`: image > **CanBuildAChainOfDependentJobsThatRunAfterOneJob**
> 
> Thanks for the identification. I'll take a look at it tomorrow.

Actually, couldn't resist. So I took a quick peek.

The hanging problem seems unrelated to this PR as it can be reproduced on Codespaces against the `main` branch.

**Comment by linkdotnet** [comment]
> > > It happes on the Codespace **only** on `net9.0`: image > > **CanBuildAChainOfDependentJobsThatRunAfterOneJob**
> > 
> > 
> > Thanks for the identification. I'll take a look at it tomorrow.
> 
> Actually, couldn't resist. So I took a quick peek.
> 
> The hanging problem seems unrelated to this PR as it can be reproduced on Codespaces against the `main` branch.

Interesting! Thanks for the heads up! Well - probably it is fine if we tackle it on `main` then.

**Comment by nulltoken** [comment]
> Interesting! Thanks for the heads up! Well - probably it is fine if we tackle it on `main` then.

Tracked through #125

File: src/NCronJob/Registry/JobRegistry.cs [hunk 6]
```diff
@@ -19,7 +21,7 @@ internal sealed class JobRegistry
     public JobDefinition GetJobDefinition<T>() => allJobs.First(j => j.Type == typeof(T));
 
     public JobDefinition? FindJobDefinition(Type type)
```
Comment (linkdotnet) [inline src/NCronJob/Registry/JobRegistry.cs:23]: I think we can remove the "TODO" itself. In its current state we only have a jobdefinition.

File: src/NCronJob/Execution/JobExecutor.cs [hunk 7]
```diff
@@ -154,8 +154,8 @@ public void InformDependentJobs(JobExecutionContext context, bool success)
 
         var jobRun = context.JobRun;
         var dependencies = success
-            ? jobRegistry.GetDependentSuccessJobTypes(jobRun.JobDefinition.Type)
-            : jobRegistry.GetDependentFaultedJobTypes(jobRun.JobDefinition.Type);
+            ? jobRegistry.GetDependentSuccessJobTypes(jobRun.JobDefinition)
```
Comment (linkdotnet) [inline src/NCronJob/Execution/JobExecutor.cs:157]: Would it make sense to remove the jobRegistry's `GetDependentSuccessJobTypes` and hold this information directly on the jobdefinition or would it be to convoluted?

File: src/NCronJob/Registry/JobRegistry.cs [hunk 8]
```diff
@@ -167,4 +171,37 @@ public int GetHashCode(JobDefinition obj) => HashCode.Combine(
...
+        //
+        // Maybe should a DependentJobDefinition type spawn?
+
+        public static readonly DependentJobDefinitionEqualityComparer Instance = new();
+
+        public bool Equals(JobDefinition? x, JobDefinition? y) =>
+            (x is null && y is null) || (x is not null && y is not null
+                                         && x.Type == y.Type && x.Type != typeof(DynamicJobFactory)
+                                         && x.Parameter == y.Parameter
+                                         //&& x.CronExpression == y.CronExpression
```
Comment (linkdotnet) [inline src/NCronJob/Registry/JobRegistry.cs:192]: If not needed, I would remove the commented out code.

File: tests/NCronJob.Tests/NCronJob.Tests.csproj [hunk 9]
```diff
@@ -33,12 +33,15 @@
...
+  </ItemGroup>
 
-    <ItemGroup>
-      <ProjectReference Include="..\..\src\NCronJob\NCronJob.csproj" />
-    </ItemGroup>
+  <ItemGroup>
+    <ProjectReference Include="..\..\src\NCronJob\NCronJob.csproj" />
+  </ItemGroup>
 
+  <ItemGroup>
```
Comment (linkdotnet) [inline tests/NCronJob.Tests/NCronJob.Tests.csproj:44]: Can be removed and should be tackled with #125

File: tests/NCronJob.Tests/xunit.runner.json [hunk 10]
```diff
@@ -0,0 +1,5 @@
+{
```
Comment (linkdotnet) [inline tests/NCronJob.Tests/xunit.runner.json:1]: The same here.

File: src/NCronJob/Registry/JobRegistry.cs (hunk 6 above)
Comment (nulltoken) [reply src/NCronJob/Registry/JobRegistry.cs:23]: In that context, how about replacing `FirstOrDefault()` by `SingleOrDefault()`?

This would enforce the expected intent of the design or would allow to not swallow potential issues.

File: src/NCronJob/Registry/JobRegistry.cs (hunk 8 above)
Comment (nulltoken) [reply src/NCronJob/Registry/JobRegistry.cs:192]: No problem. I left it commented for you to notice the change. I'll drop it with the next push.

File: src/NCronJob/Registry/JobRegistry.cs (hunk 6 above)
Comment (linkdotnet) [reply src/NCronJob/Registry/JobRegistry.cs:23]: I am a big fan of "fail fast". Do we have an option for `v3` to throw an exception when we add a duplicate? 
In v4 `UseNCronJob` could be our savior - but not sure what can be done for v3.

If there isn't anything, maybe a custom exception might be more appropriate. Not sure what a user can do if he receives the `InvalidOperationException` with "Sequence contains more than one element" message.

Comment (nulltoken) [reply src/NCronJob/Registry/JobRegistry.cs]: I've eventually only removed the TODO.

The code actually doesn't allow duplicates. In that context, Using `FirstOrDefault()` or `SingleOrDefault()` is similar.

However, the way the code deals with duplicates isn't uniform, from a user standpoint. A such, I've created #128 (which I think should be dealt with in the context of v4 as it will certainly generate a change the behavior).

File: tests/NCronJob.Tests/xunit.runner.json (hunk 10 above)
Comment (nulltoken) [reply tests/NCronJob.Tests/xunit.runner.json]: Fixed

File: tests/NCronJob.Tests/NCronJob.Tests.csproj (hunk 9 above)
Comment (nulltoken) [reply tests/NCronJob.Tests/NCronJob.Tests.csproj]: Fixed

File: src/NCronJob/Registry/JobRegistry.cs (hunk 8 above)
Comment (nulltoken) [reply src/NCronJob/Registry/JobRegistry.cs]: Fixed

File: src/NCronJob/Execution/JobExecutor.cs (hunk 7 above)
Comment (nulltoken) [reply src/NCronJob/Execution/JobExecutor.cs:157]: I don't know yet. I'll work on this and `DepedentJobRegistryEntry` in a follow up PR.

File: src/NCronJob/Configuration/Builder/DependentJobRegistryEntry.cs (hunk 5 above)
Comment (linkdotnet) [reply src/NCronJob/Configuration/Builder/DependentJobRegistryEntry.cs:5]: Agreed.
> Does the test do what you'd expect?
Yes

File: src/NCronJob/Configuration/Builder/NCronJobOptionBuilder.cs [hunk 11]
```diff
@@ -190,13 +195,16 @@ internal class StartupStage<TJob> : IStartupStage<TJob> where TJob : class, IJob
     private readonly ConcurrencySettings settings;
     private readonly JobRegistry jobRegistry;
     private readonly JobOptionBuilder jobOptionBuilder;
+    private readonly ICollection<JobDefinition> jobDefinitions;
```
Comment (linkdotnet) [inline src/NCronJob/Configuration/Builder/NCronJobOptionBuilder.cs:198]: nitpick: I would like to keep it a `IReadOnlyCollection` so that the API is telling that this collection isn't going to change somewhere.

File: src/NCronJob/Configuration/Builder/NCronJobOptionBuilder.cs [hunk 12]
```diff
@@ -246,15 +254,18 @@ internal class NotificationStage<TJob> : INotificationStage<TJob> where TJob : c
     private readonly IServiceCollection services;
     private readonly ConcurrencySettings settings;
     private readonly JobRegistry jobRegistry;
+    private readonly ICollection<JobDefinition> jobDefinitions;
 
     internal NotificationStage(
         IServiceCollection services,
+        ICollection<JobDefinition> jobDefinitions,
```
Comment (linkdotnet) [inline src/NCronJob/Configuration/Builder/NCronJobOptionBuilder.cs:261]: Some would apply here

**Review by linkdotnet — APPROVED** [review]

File: src/NCronJob/Registry/JobRegistry.cs (hunk 4 above)
Comment (linkdotnet) [reply src/NCronJob/Registry/JobRegistry.cs:177]: We can invest some time into a new type `DependentJobDefinition`. It feels like it might be useful.
But not in this PR :D

File: src/NCronJob/Configuration/Builder/NCronJobOptionBuilder.cs (hunk 11 above)
Comment (nulltoken) [reply src/NCronJob/Configuration/Builder/NCronJobOptionBuilder.cs]: Fixed

File: src/NCronJob/Configuration/Builder/NCronJobOptionBuilder.cs (hunk 12 above)
Comment (nulltoken) [reply src/NCronJob/Configuration/Builder/NCronJobOptionBuilder.cs]: Fixed here as well and everywhere else.

**Comment by nulltoken** [comment]
Changelog has been updated as well.

**Comment by linkdotnet** [comment]
Good work! I will directly make a new release!
