### PR TITLE
fix: Check for disposed states

### LINKED ISSUE #172: QueueWorker ObjectDisposedException: The CancellationTokenSource has been disposed.
**Describe the bug**

While onboarding a new project at $DAYJOB, the CI started to complain

```
2025-01-21T14:44:30.8930169Z    [Test Collection Cleanup Failure (FakeStandardAuthenticatedServerSetupCollection)]:
System.ObjectDisposedException : The CancellationTokenSource has been disposed.
2025-01-21T14:44:30.8930752Z Object name: 'System.Threading.CancellationTokenSource+Linked1CancellationTokenSource'.
2025-01-21T14:44:30.8931223Z   Stack Trace:
2025-01-21T14:44:30.8931762Z      at NCronJob.QueueWorker.StopAsync(CancellationToken cancellationToken)
2025-01-21T14:44:30.8932320Z    at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
2025-01-21T14:44:30.8932908Z    at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
2025-01-21T14:44:30.8933376Z    at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.DisposeAsync()
2025-01-21T14:44:30.8933829Z    at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose(Boolean disposing)
2025-01-21T14:44:30.8934363Z    at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose()
2025-01-21T14:44:30.8934829Z    at Alba.AlbaHost.Dispose() in /_/src/Alba/AlbaHost.cs:line 125
2025-01-21T14:44:30.8939828Z    at Tests.Helpers.RawServer.Dispose() in /home/vsts/work/1/s/backend/test/Helpers/TestServerSetup.cs:line 237
```

My rough understanding of the call stack is that while xUnit disposes a Collection Fixture, the said collection fixture disposes a Alba hosted test intance of the web app under test, which eventually cascades to NCronJob.

@linkdotnet I have nothing much more than that for now. I'll try to dig a little deeper and report back.
Or otherwise will try to bisect this thing into a minimal repro case (but this may take some time)

Meanwhile, if you've got mind-debugging abilities, I'd be a taker :wink:

### PR DESCRIPTION
**Pull request by linkdotnet**
Attempt to fix #172

### CODE REVIEW

File: src/NCronJob/Scheduler/JobWorker.cs [hunk 1]
```diff
@@ -120,7 +120,7 @@ private async Task DispatchJobForProcessing(
         }
         finally
         {
-            if (shouldReleaseSemaphore)
+            if (shouldReleaseSemaphore && jobQueueManager.IsDisposed)
```
Comment (nulltoken) [inline src/NCronJob/Scheduler/JobWorker.cs:123]: I don't know much about this part of the codebase so please consider every comment with very suspicious eyes.

The semaphore seems to be issued by the JobQueueManager

```
 var semaphore = jobQueueManager.GetOrAddSemaphore(queueName, concurrencyLimit);
 ```
 
So does it make sense to release it (and eventually invoke a Dispose() a layer down call) when the jobQueueManager is already disposed?

It looks like that upon the jobQueueManager disposal, the semaphores are disposed, aren't they?
```
    public void Dispose()
    {
        if (IsDisposed)
            return;

        foreach (var jobQueue in jobQueues.Values)
        {
            jobQueue.CollectionChanged -= CallCollectionChanged;
        }

        foreach (var semaphore in semaphores.Values)
        {
            semaphore.Dispose();
        }

        foreach (var cts in jobCancellationTokens.Values)
        {
            cts.Dispose();
        }

        jobQueues.Clear();
        semaphores.Clear();
        jobCancellationTokens.Clear();

        IsDisposed = true;
    }
```

Would my understanding of the code be correct (*narrator: "\*cough\* very unlikely \*cough\*"*), the release of the semaphore in JobWorker when the jobQueueManager is already Disposed may actually trigger an ObjectDisposedException, no?

**Once again: big disclaimer. bad coder. little knowledge. scary linked cancellation tokens all around.**

**Comment by nulltoken** [comment]
With regards to the build failure. maybe adding `--logger "console;verbosity=detailed"` to the `dotnet` test command might help get a better insight?

File: src/NCronJob/Scheduler/JobWorker.cs (hunk 1 above)
Comment (linkdotnet) [reply src/NCronJob/Scheduler/JobWorker.cs]: That was a big uppsie from my side - it should (and now is) `&& !jobQueueManager.IsDispose`

**Comment by linkdotnet** [comment]
> With regards to the build failure. maybe adding `--logger "console;verbosity=detailed"` to the `dotnet` test command might help get a better insight?

Yeah - I just screwed up royaly and good that we have tests

**Review by nulltoken — APPROVED** [review]
Let's give it a try.

Can you cut a preview release?

**Comment by linkdotnet** [comment]
> Let's give it a try.
> 
> Can you cut a preview release?

Yeah
